### ISSUE TITLE
部分中文发音人合成失败

### ISSUE THREAD

**Issue by wjddd** [viitor-ai/viitor-voice#2]
您好，使用以下发音人合成的时候会出现报错：
```
0、4、13、15、20、21、33、35、39、42、43、49、60、61、66、70、71、74
```

具体报错信息：
```shell
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/.../main.py", line 64, in <module>
[rank0]:     audios = run([speaker], ["我觉得我还是可以抢救一下的。"])
[rank0]:   File "/home/.../main.py", line 48, in run
[rank0]:     audios = tte_engine_chs.batch_infer(
[rank0]:   File "/home/.../utils/offline_inference.py", line 69, in batch_infer
[rank0]:     audios = self.batch_decode_audios(results)
[rank0]:   File "/home/.../utils/offline_inference.py", line 79, in batch_decode_audios
[rank0]:     audio_hat_all = self.snac_model.decode(codes)
[rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/snac.py", line 89, in decode
[rank0]:     z_q = self.quantizer.from_codes(codes)
[rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/vq.py", line 97, in from_codes
[rank0]:     z_q += z_q_i
[rank0]: RuntimeError: The size of tensor a (2036) must match the size of tensor b (2032) at non-singleton dimension 2
```

**Comment by MrWaterZhou** [comment]
> 您好，使用以下发音人合成的时候会出现报错：
> 
> ```
> 0、4、13、15、20、21、33、35、39、42、43、49、60、61、66、70、71、74
> ```
> 
> 具体报错信息：
> 
> ```shell
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/.../main.py", line 64, in <module>
> [rank0]:     audios = run([speaker], ["我觉得我还是可以抢救一下的。"])
> [rank0]:   File "/home/.../main.py", line 48, in run
> [rank0]:     audios = tte_engine_chs.batch_infer(
> [rank0]:   File "/home/.../utils/offline_inference.py", line 69, in batch_infer
> [rank0]:     audios = self.batch_decode_audios(results)
> [rank0]:   File "/home/.../utils/offline_inference.py", line 79, in batch_decode_audios
> [rank0]:     audio_hat_all = self.snac_model.decode(codes)
> [rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/snac.py", line 89, in decode
> [rank0]:     z_q = self.quantizer.from_codes(codes)
> [rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/vq.py", line 97, in from_codes
> [rank0]:     z_q += z_q_i
> [rank0]: RuntimeError: The size of tensor a (2036) must match the size of tensor b (2032) at non-singleton dimension 2
> ```

目前中文对于不同语速的训练不够充分, 导致输出的token无法被正确解码, 我们近期会更新
您可以尝试变换一下speed_id=1, 对于一些音色会有改善

**Comment by wjddd** [comment]
> > 您好，使用以下发音人合成的时候会出现报错：
> > ```
> > 0、4、13、15、20、21、33、35、39、42、43、49、60、61、66、70、71、74
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 具体报错信息：
> > ```shell
> > [rank0]: Traceback (most recent call last):
> > [rank0]:   File "/home/.../main.py", line 64, in <module>
> > [rank0]:     audios = run([speaker], ["我觉得我还是可以抢救一下的。"])
> > [rank0]:   File "/home/.../main.py", line 48, in run
> > [rank0]:     audios = tte_engine_chs.batch_infer(
> > [rank0]:   File "/home/.../utils/offline_inference.py", line 69, in batch_infer
> > [rank0]:     audios = self.batch_decode_audios(results)
> > [rank0]:   File "/home/.../utils/offline_inference.py", line 79, in batch_decode_audios
> > [rank0]:     audio_hat_all = self.snac_model.decode(codes)
> > [rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/snac.py", line 89, in decode
> > [rank0]:     z_q = self.quantizer.from_codes(codes)
> > [rank0]:   File "/home/miniconda3/envs/viitor_voice/lib/python3.10/site-packages/snac/vq.py", line 97, in from_codes
> > [rank0]:     z_q += z_q_i
> > [rank0]: RuntimeError: The size of tensor a (2036) must match the size of tensor b (2032) at non-singleton dimension 2
> > ```
> 
> 目前中文对于不同语速的训练不够充分, 导致输出的token无法被正确解码, 我们近期会更新 您可以尝试变换一下speed_id=1, 对于一些音色会有改善

十分感谢~我尝试了speed=1，部分音色确实有改善，但合成音频的时候仍有断句停顿较长的问题。
