### ISSUE TITLE
模型训练预处理步骤报错：Error when binding input: There's no data transfer registered for copying tensors from Device to Device

### ISSUE THREAD

**Issue by wjddd** [viitor-ai/viitor-voice#3]
参考[train_example.md](https://github.com/viitor-ai/viitor-voice/blob/main/train_example.md)，运行[preprocess.py](https://github.com/viitor-ai/viitor-voice/blob/main/preprocess.py)时出现以下报错：

```shell
Traceback (most recent call last):
  File "/home/.../preprocess.py", line 294, in <module>
    main()
  File "/home/.../preprocess.py", line 288, in main
    data = handler(audio, text)
  File "/opt/conda/envs/viitor/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/.../preprocess.py", line 218, in __call__
    speaker_encode = self.get_speaker_encode(audio)
  File "/home/.../preprocess.py", line 200, in get_speaker_encode
    speaker_embedding = self.speaker_model(feat_v2).cpu().numpy()
  File "/home/.../preprocess.py", line 105, in __call__
    self.binding.bind_input(
  File "/opt/conda/envs/viitor/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 609, in bind_input
    self._iobinding.bind_input(
RuntimeError: Error when binding input: There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:0] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]
```

相关依赖：
```
Package            Version
------------------ -----------
aiohappyeyeballs   2.4.4
aiohttp            3.11.9
aiosignal          1.3.1
async-timeout      5.0.1
attrs              24.2.0
Brotli             1.0.9
certifi            2024.8.30
charset-normalizer 3.3.2
coloredlogs        15.0.1
datasets           3.1.0
dill               0.3.8
einops             0.8.0
filelock           3.13.1
flatbuffers        24.3.25
frozenlist         1.5.0
fsspec             2024.9.0
gmpy2              2.1.2
huggingface-hub    0.26.3
humanfriendly      10.0
idna               3.7
Jinja2             3.1.4
joblib             1.4.2
MarkupSafe         2.1.3
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mpmath             1.3.0
multidict          6.1.0
multiprocess       0.70.16
networkx           3.3
numpy              1.24.0
onnxruntime-gpu    1.20.1
packaging          24.2
pandas             2.2.3
pillow             11.0.0
pip                24.2
propcache          0.2.1
protobuf           5.29.0
pyarrow            18.1.0
PySocks            1.7.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
requests           2.32.3
scikit-learn       1.5.2
scipy              1.12.0
setuptools         75.1.0
six                1.16.0
snac               1.2.1
sympy              1.13.2
threadpoolctl      3.5.0
torch              2.4.0
torchaudio         2.4.0
torchvision        0.19.0
tqdm               4.67.1
triton             3.0.0
typing_extensions  4.11.0
tzdata             2024.2
urllib3            2.2.3
wheel              0.44.0
xxhash             3.5.0
yarl               1.18.3
```

**Comment by MrWaterZhou** [comment]
这个脚本使用了tensorrt作为onnx的backend, 没有安装的话, 可能会fallback到cpu推理
feat_v2在cuda, onnx在cpu, 会导致设备不匹配

P.S. 
目前我们实验的结论是, 使用speaker embedding的方法对不同说话人泛化能力有限, 计划废弃; 之后会更新, 流程会简化很多

**Comment by wjddd** [comment]
> 这个脚本使用了tensorrt作为onnx的backend, 没有安装的话, 可能会fallback到cpu推理 feat_v2在cuda, onnx在cpu, 会导致设备不匹配
> 
> P.S. 目前我们实验的结论是, 使用speaker embedding的方法对不同说话人泛化能力有限, 计划废弃; 之后会更新, 流程会简化很多

了解，感谢回复~

**Comment by MrWaterZhou** [comment]
我们更新了代码以及新模型, 相比之前简化了不少, 欢迎尝试~
