### ISSUE TITLE
模型预处理报错

### ISSUE THREAD

**Issue by wjddd** [viitor-ai/viitor-voice#6]
您好，我在运行以下命令的时候：
```
python viitor_voice/preprocess/preprocess_model.py tool_models/Qwen2-0.5B tool_models/Qwen2-0.5B-snac
```
出现以下报错：
```
Traceback (most recent call last):
  File "/home/.../viitor_voice/preprocess/preprocess_model.py", line 20, in <module>
    model.resize_position_embeddings(len(tokenizer))
  File "/opt/conda/envs/tts/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2535, in resize_position_embeddings
    raise NotImplementedError(
NotImplementedError: `resize_position_embeddings` is not implemented for <class 'transformers.models.qwen2.modeling_qwen2.Qwen2ForCausalLM'>`. To implement it, you should overwrite this method in the class <class 'transformers.models.qwen2.modeling_qwen2.Qwen2ForCausalLM'> in `modeling_transformers.models.qwen2.modeling_qwen2.py`
```
相关依赖如下：
```
tokenizers                        0.21.0
transformers                      4.47.1
```

**Comment by MrWaterZhou** [comment]
有个错误, 已经修复了
